In [1]:
%matplotlib inline
import pandas as pd

import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

In [2]:
musica = pd.read_excel('top10s.xlsx')

del musica['Num']

data = pd.DataFrame(musica).head()

data

,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,"Hey, Soul Sister",Train,neo mellow,2010.0,97.0,89.0,67.0,-4.0,8.0,80.0,217.0,19.0,4.0,83.0
1,Love The Way You Lie,Eminem,detroit hip hop,2010.0,87.0,93.0,75.0,-5.0,52.0,64.0,263.0,24.0,23.0,82.0
2,TiK ToK,Kesha,dance pop,2010.0,120.0,84.0,76.0,-3.0,29.0,71.0,200.0,10.0,14.0,80.0
3,Bad Romance,Lady Gaga,dance pop,2010.0,119.0,92.0,70.0,-4.0,8.0,71.0,295.0,0.0,4.0,79.0
4,Just the Way You Are,Bruno Mars,pop,2010.0,109.0,84.0,64.0,-5.0,9.0,43.0,221.0,2.0,4.0,78.0